"use client";

import { useState } from "react";
import { siteConfig } from "@/lib/site-config";

export function SiteHeader() {
  const [isOpen, setIsOpen] = useState(false);
  const closeMenu = () => setIsOpen(false);
  return <header className="relative border-b border-[#15231d]/15"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><a href="#top" className="flex items-center gap-3" onClick={closeMenu}><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[#9b7a3c] text-lg font-semibold text-[#9b7a3c]" aria-hidden="true">S</span><span><span className="block font-serif text-lg font-semibold tracking-wide">{siteConfig.shortName}</span><span className="block text-[10px] uppercase tracking-[0.3em] text-[#15231d]/60">{siteConfig.descriptor}</span></span></a><nav className="hidden items-center gap-8 text-sm font-medium lg:flex" aria-label="Primary navigation">{siteConfig.navigation.map((item) => <a key={item.href} className="transition hover:text-[#9b7a3c]" href={item.href}>{item.label}</a>)}</nav><a href="#contact" className="hidden rounded-full bg-[#15231d] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#9b7a3c] sm:inline-flex">Book Consultation</a><button type="button" className="inline-flex h-11 w-11 items-center justify-center rounded-full border border-[#15231d]/20 text-[#15231d] lg:hidden" aria-label="Toggle navigation menu" aria-expanded={isOpen} aria-controls="mobile-navigation" onClick={() => setIsOpen((open) => !open)}><span className="text-xl" aria-hidden="true">{isOpen ? "×" : "☰"}</span></button></div>{isOpen && <nav id="mobile-navigation" className="absolute inset-x-0 top-full z-20 border-b border-[#15231d]/15 bg-[#f5f1e8] px-6 py-6 shadow-xl lg:hidden" aria-label="Mobile navigation"><div className="mx-auto flex max-w-7xl flex-col gap-1">{siteConfig.navigation.map((item) => <a key={item.href} href={item.href} className="rounded-xl px-4 py-3 text-base font-medium transition hover:bg-[#15231d] hover:text-white" onClick={closeMenu}>{item.label}</a>)}<a href="#contact" className="mt-3 rounded-full bg-[#15231d] px-5 py-3 text-center text-sm font-semibold text-white" onClick={closeMenu}>Book Consultation</a></div></nav>}</header>;
}
